language: cpp
dist: trusty
os: linux
sudo: required
git:
  depth: 1

branches:
  only:
  - master
  - travis-test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - libyajl-dev
      - libgtest-dev
      - g++-6
      - libpthread-stubs0-dev
        # Without clang clang-tidy gives weird errors
      - clang-4.0
      - clang-tidy-4.0
env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pushd /usr/src/gtest
  - sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib
  - popd
  - sudo ln -s `which clang-tidy-4.0` /usr/bin/clang-tidy

script:
  - mkdir build
  - cd build
  - cmake ../ -DWITH_TESTS=True && make && make test && make check
